apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  # namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: busybox
        image: busybox
        imagePullPolicy: Always
        command: ['sh', '-c', "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: elasticsearch-storage-class
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xmx1g -Xms1g
        - name: bootstrap.memory_lock
          value: "true"
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.authc.api_key.enabled
          value: "true"
        - name: xpack.monitoring.collection.enabled 
          value: "true"
        - name: xpack.security.enrollment.enabled 
          value: "true" 
        - name: xpack.security.authc.token.enabled  
          value: "true"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elasticsearch-password
              name: elasticsearch-secrets
        resources:
          limits:
            cpu: 1500m
            memory: 5Gi
          requests:
            cpu: 250m
            memory: 5Gi
        ports:
        - name: elasticsearch
          containerPort: 9200
        volumeMounts:
        - name: elasticsearch-storage-class
          mountPath: /usr/share/elasticsearch/data
          subPath: data
      volumes:
      - name: elasticsearch-storage-class
        persistentVolumeClaim:
          claimName: elasticsearch-pvc