apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: development
spec:
  storageClassName: elasticsearch-storage-class
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: development
spec:
  storageClassName: elasticsearch-storage-class
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
