apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-pg
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
  - name: res
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: inter-node
    port: 9300
    targetPort: 9300
    protocol: TCP
