apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: huddlehub
build:
  artifacts:
    - image: sergeyarenzon/huddlehub-auth
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: sergeyarenzon/huddlehub-user
      context: services/user
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: redis
        repo: https://charts.bitnami.com/bitnami
        remoteChart: redis
        valuesFiles:
          - k8s/minikube/redis/values.yaml
      - name: user-db
        chartPath: k8s/helm/user-db/
        valuesFiles:
          - k8s/helm/user-db/values.yaml

  rawYaml:
    # SECRETS
    - k8s/minikube/secrets/globals.yaml

    # GATEWAY
    - k8s/minikube/gateway/ingress.yaml
    - k8s/minikube/gateway/service.yaml

    # RABBITMQ
    # - k8s/minikube/rabbitmq/deployment.yaml
    # - k8s/minikube/rabbitmq/persistentVolume.yaml
    # - k8s/minikube/rabbitmq/service.yaml
    # - k8s/minikube/rabbitmq/storageClass.yaml
    # - k8s/minikube/rabbitmq/configMap.yaml

    # USER
    - k8s/minikube/secrets/globals.yaml
    - k8s/minikube/user/deployment.yaml
    - k8s/minikube/user/service.yaml
    
    # AUTH
    - k8s/minikube/auth/*