apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: huddlehub
build:
  artifacts:
    - image: sergeyarenzon/huddlehub-auth
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: sergeyarenzon/huddlehub-user
      context: services/user
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: sergeyarenzon/huddlehub-tour
      context: services/tour
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: gateway
        chartPath: k8s/helm/gateway/
        valuesFiles:
          - k8s/helm/gateway/values.yaml
      - name: secrets
        chartPath: k8s/helm/secrets/
        valuesFiles:
          - k8s/helm/secrets/values.yaml
      # - name: redis
      #   repo: https://charts.bitnami.com/bitnami
      #   remoteChart: redis
      #   valuesFiles:
          # - k8s/minikube/redis/values.yaml
      - name: user-db
        chartPath: k8s/helm/user-db/
        valuesFiles:
          - k8s/helm/user-db/values.yaml
      - name: tour-db
        chartPath: k8s/helm/tour-db/
        valuesFiles:
          - k8s/helm/tour-db/values.yaml
      - name: ingress-nginx
        chartPath: k8s/helm/ingress-nginx/
        valuesFiles:
          - k8s/helm/ingress-nginx/values.yaml
      - name: auth
        chartPath: k8s/helm/auth/
        valuesFiles:
          - k8s/helm/auth/values.yaml
      - name: user
        chartPath: k8s/helm/user/
        valuesFiles:
          - k8s/helm/user/values.yaml
      - name: tour
        chartPath: k8s/helm/tour/
        valuesFiles:
          - k8s/helm/tour/values.yaml
      # - name: kafka
      #   repo: https://charts.bitnami.com/bitnami
      #   remoteChart: kafka
      #   valuesFiles:
      #      - k8s/helm/kafka/values.yaml

  # rawYaml:
  #   # GATEWAY
  #   - k8s/minikube/gateway/*