
# POST http://localhost:4002
# Content-Type: application/json

# {
#   "firs_name": "xsdfx1xasdx2sssdfsdfdfdfsdf3",
#   "last_name": "Arens1dfzon22sdfsdfsdf13",
#   "email": "asa2123s1sdfdf22@sdfsdfgmail.com",
#   "image_url": "http://www.go1ogl12sdfsdfsdf3e222.com"
#  }


# GET http://localhost:4002
# Content-Type: application/json




# GET http://huddlehub.io/api/user/languages
# Content-Type: application/json



GET http://huddlehub.io/api/tour/category
# curl 'http://huddlehub.io/api/user/languages' \
#   -H 'Accept: application/json, text/plain, */*' \
#   -H 'Accept-Language: en,ru;q=0.9,he;q=0.8' \
#   -H 'Cache-Control: no-cache' \
#   -H 'Connection: keep-alive' \
#   -H 'Origin: http://localhost:3000' \
#   -H 'Pragma: no-cache' \
#   -H 'Referer: http://localhost:3000/' \
#   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'