
POST http://localhost:4002
Content-Type: application/json

{
  "first_name": "Sergey2121212",
  "last_name": "Arenzon2",
  "email": "asa2@gmail.com",
  "image_url": "http://www.google2.com"
 }


# GET http://localhost:4002
# Content-Type: application/json
