replicaCount: 1

image:
  repository: sergeyarenzon/huddlehub-user
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 150Mi

configMaps:
  user-db:
    name: user-db-config
    keys:
      POSTGRES_HOST: user-db
      POSTGRES_PORT: "5432"

database:
  url: "postgresql://postgres:postgres@user-db:5432/postgres?schema=public"
  host: "user-db"
  port: 5432
  name: "user"
  user: "postgres"
  password: "postgres"