replicaCount: 1

image:
  repository: sergeyarenzon/huddlehub-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 150Mi

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 80

env:
  NODE_ENV: production
  JWT_MAX_AGE: 3600000
  # Add other environment variables as needed

# configMaps:
#   rabbitmq:
#     name: rabbitmq-config

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: auth_db
  persistence:
    size: 8Gi


secrets:
  global:
    name: global-secrets
    keys:
      jwt-secret: jwt-secret 