apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-nginx.fullname" . }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.controller.service.ports.http | default 80 }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.controller.service.ports.https | default 443 }}
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
