image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 150Mi

persistence:
  enabled: true
  storageClass: user-db-storage-class
  size: 1Gi
  accessMode: ReadWriteOnce
  hostPath: /var/lib/postgresql/data

config:
  POSTGRES_HOST: postgresql://postgres:postgres@user-db.default.svc.cluster.local:5432/postgres?schema=public
  POSTGRES_PORT: "5432"
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRESS_DB: user
  PGDATA: "/var/lib/postgresql/data/user"

service:
  type: ClusterIP
  port: 5432

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3 