apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.primary.persistence.size }}
  {{ if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }} 