apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: auth
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP 