apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  # namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management-alpine
          env: 
          - name: RABBITMQ_DEFAULT_USER
            value: guest
          - name: RABBITMQ_DEFAULT_PASS
            value: guest
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests: 
              memory: "150Mi"
              cpu: "100m"
          ports:
          - name: rabbitmq
            containerPort: 5672
            protocol: TCP
          - name: mgmt
            containerPort: 15672
            protocol: TCP
          volumeMounts:
          - name: rabbitmq-storage-class
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage-class
          persistentVolumeClaim:
            claimName: rabbitmq-pvc  
