apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  # namespace: development
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: rabbitmq
    protocol: TCP
  - name: mgmt
    port: 15672
    targetPort: mgmt
    protocol: TCP
