apiVersion: storage.k8s.io/v1
kind: StorageClass  
metadata:
  name: rabbitmq-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete


