import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import TopBar from "./topbar";
import { Roboto_Serif } from 'next/font/google'


const robotoMono = Roboto_Serif({
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-roboto-serif',
  style: ['normal', 'italic']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} antialiased`}
        >
          <TopBar />
          {children}
        </body>
      </html>
    </Providers>
  );
}
