# upate passwords for masterauth and requirepass
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  # namespace: development
data:
  REDIS_HOST: redis://myredispass@redis.development.svc.cluster.local:6379
  redis.conf: |
    requirepass myredispass
