apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  # namespace: development
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"