
architecture: standalone
name: redis
auth:
  enabled: false
  password: "redis"  # Change this in production!

master:
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
securityContext:
  runAsUser: 1001
  runAsNonRoot: true
metrics:
  enabled: false  # Enables Prometheus metrics

service:
  type: ClusterIP
  port: 6379
