replicaCount: 1

image:
  repository: sergeyarenzon/huddlehub-tour
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 4003

env:
  PORT: 4003

database:
  url: "postgresql://postgres:postgres@tour-db:5432/postgres?schema=public"
  host: "tour-db"
  port: 5432
  name: "tour"
  user: "postgres"
  password: "postgres"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi 

# configMaps:
#   tour-db:
#     name: tour-db-config
#     keys:
#       POSTGRES_HOST: tour-db
#       POSTGRES_PORT: 5432