apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-config
  # namespace: development
data:
  POSTGRES_HOST: postgresql://postgres:postgres@user-db.default.svc.cluster.local:5432/postgres?schema=public
  POSTGRES_PORT: "5432"
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRESS_DB: user
  PGDATA: "/var/lib/postgresql/data/user"