apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  # namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: user-db
        image: postgres
        envFrom:
        - configMapRef:
            name: user-db-config # This references your ConfigMap
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: "150Mi"
            cpu: "100m"
        ports:
        - name: user-db
          containerPort: 5432
        volumeMounts:
        - name: user-db-storage-class
          mountPath: /var/lib/postgresql/data
          subPath: user
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: user-db-storage-class
        persistentVolumeClaim:
          claimName: user-db-pvc