apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pg-pv
  namespace: development
spec:
  storageClassName: user-pg-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pg-pvc
  namespace: development
spec:
  storageClassName: user-pg-storage-class
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
