apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  # namespace: development
spec:
  storageClassName: user-db-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
  # namespace: development
spec:
  storageClassName: user-db-storage-class
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
