apiVersion: v1
kind: Secret
metadata:
  name: user-db-secrets
  # namespace: development
type: Opaque
data:
  # postgres
  pg-user-user: cG9zdGdyZXM=
  #  postgres
  pg-user-password: cG9zdGdyZXM=
  # user
  pg-user-db-name: dXNlcg==
  # /var/lib/postgresql/data/user
  pg-user-data: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3VzZXI=
