apiVersion: v1
kind: Service
metadata:
  name: user-pg
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: user-pg
  ports:
  - name: user-pg
    port: 5432
    targetPort: 5432
    protocol: TCP
