apiVersion: v1
kind: Service
metadata:
  name: user-db
  # namespace: development
spec:
  type: ClusterIP
  selector:
    app: user-db
  ports:
  - name: user-db
    port: 5432
    targetPort: 5432
    protocol: TCP
