version: 2.27.1

services: 
  auth-api:
    build:
      context: ../services/auth
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      ADDRESS: 0.0.0.0 
      PORT: 8080
      NODE_ENV: development
    volumes:
      - ../services/auth/src:/app/src
      - /code/node_modules
    networks:
      - huddlehub-network
    
  users-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: huddle_hub
    ports:
      - 5432:5432
    networks:
      - huddlehub-network
    
  pgadmin-users:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - huddlehub-network


  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      API_URL: "http://localhost:8080"
      PORT: 3000
    command: npm run dev
    volumes:
      - ../client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - auth-api
    networks:
      - huddlehub-network

  # nginx:
  #   build:
  #     context: ../services/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - huddlehub-network
  #   depends_on:
  #     - auth-api

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - huddlehub-network
    depends_on:
      - auth-api
      - client

networks:
  huddlehub-network:
    driver: bridge