version: 2.27.1

services: 
  auth-api:
    build:
      context: ../services/auth
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    command: npm run dev
    env_file:
      - ../services/auth/.env
    volumes:
      - ../services/auth/src:/app/src
      - /code/node_modules
    
  users-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: huddle_hub
    ports:
      - 5432:5432
    
  pgadmin-users:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ../client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - auth-api

