version: 2.27.1

services: 
  server:
    build:
      context: ../services/server
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      ADDRESS: 0.0.0.0 
      PORT: 8080
      NODE_ENV: development
      DATABASE_URL: "postgresql://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@pg-db:${PG_DATABASE_PORT}/${PG_DATABASE_DB}?schema=public"
    volumes:
      - ../services/server/src:/app/src
      - ../services/server/prisma:/app/prisma
      - /code/node_modules
    networks:
      - huddlehub-network
  auth:
    build:
      context: ../services/auth
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      ADDRESS: 0.0.0.0 
      PORT: 8081
      NODE_ENV: development
      DATABASE_URL: "postgresql://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@pg-db:${PG_DATABASE_PORT}/${PG_DATABASE_DB}?schema=public"
    volumes:
      - ../services/auth/src:/app/src
      - ../services/auth/prisma:/app/prisma
      - /code/node_modules
    networks:
      - huddlehub-network
    
  pg-db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_DATABASE_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_DB}
    ports:
      - ${PG_DATABASE_PORT}:5432
    volumes:
      - ../data/server:/var/lib/postgresql/data
    networks:
      - huddlehub-network
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - huddlehub-network


  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      API_URL: "http://localhost:8080"
      PORT: 3000
    command: npm run dev
    volumes:
      - ../client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server
    networks:
      - huddlehub-network

  # nginx:
  #   build:
  #     context: ../services/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - huddlehub-network
  #   depends_on:
  #     - auth-api

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - huddlehub-network
    depends_on:
      - server
      - client

networks:
  huddlehub-network:
    driver: bridge


volumes:
  user-data: {}