apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.15.2
        resources:
          limits:
            memory: "1Gi"
            cpu: "1500m"
          requests:
            memory: 1Gi
            cpu: 250m
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch:9200"
          - name: ELASTICSEARCH_USERNAME
            value: kibana_system
          - name: ELASTICSEARCH_PASSWORD
            value: kibana
          - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
            value: AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6N3BWZ0ItZWxSY21wMEJ0Y3ZKNTlHZw
          - name: XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS
            value: '["http://elasticsearch:9200"]'
        ports:
        - name: kibana
          containerPort: 5601
          protocol: TCP
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
          readOnly: true
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config