apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
    protocol: TCP