apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tour.fullname" . }}-migration
  labels:
    app: {{ include "tour.fullname" . }}
    job: migration
  # annotations:
    # Add a skaffold annotation to force recreation
    # "skaffold.dev/depends-on-image1": "{{ .Values.image.repository }}"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "tour.fullname" . }}
        job: migration
    spec:
      initContainers:
        - name: check-tour-db-ready
          image: busybox:latest
          command: ['sh', '-c', 
            'until nc -z -w1 {{ .Values.database.host }} {{ .Values.database.port }}; 
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              echo "Running DB migrations..." &&
              npx mikro-orm migration:up &&
              echo "Running seeders..." &&
              npx mikro-orm seeder:run
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.url }}"
      restartPolicy: Never 